# Generated by Django 5.0 on 2024-01-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
    ]
